package forestry.api.apiculture;

import net.minecraft.resources.ResourceLocation;

import static forestry.api.ForestryConstants.forestry;

/**
 * IDs of all bee species registered by base Forestry.
 */
public class ForestryBeeSpecies {
	public static final ResourceLocation FOREST = forestry("forest");
	public static final ResourceLocation MEADOWS = forestry("meadows");
	public static final ResourceLocation COMMON = forestry("common");
	public static final ResourceLocation CULTIVATED = forestry("cultivated");
	public static final ResourceLocation NOBLE = forestry("noble");
	public static final ResourceLocation MAJESTIC = forestry("majestic");
	public static final ResourceLocation IMPERIAL = forestry("imperial");
	public static final ResourceLocation DILIGENT = forestry("diligent");
	public static final ResourceLocation UNWEARY = forestry("unweary");
	public static final ResourceLocation INDUSTRIOUS = forestry("industrious");
	public static final ResourceLocation STEADFAST = forestry("steadfast");
	public static final ResourceLocation VALIANT = forestry("valiant");
	public static final ResourceLocation HEROIC = forestry("heroic");
	public static final ResourceLocation SINISTER = forestry("sinister");
	public static final ResourceLocation FIENDISH = forestry("fiendish");
	public static final ResourceLocation DEMONIC = forestry("demonic");
	public static final ResourceLocation MODEST = forestry("modest");
	public static final ResourceLocation FRUGAL = forestry("frugal");
	public static final ResourceLocation AUSTERE = forestry("austere");
	public static final ResourceLocation TROPICAL = forestry("tropical");
	public static final ResourceLocation EXOTIC = forestry("exotic");
	public static final ResourceLocation EDENIC = forestry("edenic");
	public static final ResourceLocation ENDED = forestry("ended");
	public static final ResourceLocation SPECTRAL = forestry("spectral");
	public static final ResourceLocation PHANTASMAL = forestry("phantasmal");
	public static final ResourceLocation WINTRY = forestry("wintry");
	public static final ResourceLocation ICY = forestry("icy");
	public static final ResourceLocation GLACIAL = forestry("glacial");
	public static final ResourceLocation VINDICTIVE = forestry("vindictive");
	public static final ResourceLocation VENGEFUL = forestry("vengeful");
	public static final ResourceLocation AVENGING = forestry("avenging");
	public static final ResourceLocation LEPORINE = forestry("leporine");
	public static final ResourceLocation MERRY = forestry("merry");
	public static final ResourceLocation TIPSY = forestry("tipsy");
	public static final ResourceLocation TRICKY = forestry("tricky");
	public static final ResourceLocation PATRIOTIC = forestry("patriotic");
	public static final ResourceLocation RURAL = forestry("rural");
	public static final ResourceLocation FARMERLY = forestry("farmerly");
	public static final ResourceLocation AGRARIAN = forestry("agrarian");
	public static final ResourceLocation MARSHY = forestry("marshy");
	public static final ResourceLocation MIRY = forestry("miry");
	public static final ResourceLocation BOGGY = forestry("boggy");
	public static final ResourceLocation SAVANNA = forestry("savanna");
	public static final ResourceLocation ARGIL = forestry("argil");
	public static final ResourceLocation PRIDE = forestry("pride");
	public static final ResourceLocation MONASTIC = forestry("monastic");
	public static final ResourceLocation SECLUDED = forestry("secluded");
	public static final ResourceLocation HERMITIC = forestry("hermitic");
	public static final ResourceLocation LUSH = forestry("lush");
	public static final ResourceLocation VERDANT = forestry("verdant");
	public static final ResourceLocation LUXURIANT = forestry("luxuriant");
	public static final ResourceLocation KLEPTOPLASTIC = forestry("kleptoplastic");
	public static final ResourceLocation PHOTOSYNTHETIC = forestry("photosynthetic");
	public static final ResourceLocation AUTOTROPHIC = forestry("autotrophic");
	public static final ResourceLocation PRIMEVAL = forestry("primeval");
	public static final ResourceLocation ANACHRONE = forestry("anachrone");
	public static final ResourceLocation CHRONOFUGE = forestry("chronofuge");
	public static final ResourceLocation AQUATIC = forestry("aquatic");
	public static final ResourceLocation PIRATE = forestry("pirate");
	public static final ResourceLocation PRISMATIC = forestry("prismatic");
	public static final ResourceLocation ABYSSAL = forestry("abyssal");
	public static final ResourceLocation SHULKING = forestry("shulking");
	public static final ResourceLocation EMBITTERED = forestry("embittered");
	public static final ResourceLocation SPITEFUL = forestry("spiteful");
	public static final ResourceLocation SEETHING = forestry("seething");
	public static final ResourceLocation WARPED = forestry("warped");
	public static final ResourceLocation ZOMBIFIED = forestry("zombified");
	public static final ResourceLocation SCULK = forestry("sculk");
	public static final ResourceLocation VANILLA = forestry("vanilla");
	public static final ResourceLocation STONE = forestry("stone");
	public static final ResourceLocation GRANITE = forestry("granite");
	public static final ResourceLocation ANDESITE = forestry("andesite");
	public static final ResourceLocation DIORITE = forestry("diorite");
	public static final ResourceLocation DEEPSLATE = forestry("deepslate");
	public static final ResourceLocation STRUCTURED = forestry("structured");
	public static final ResourceLocation MINERAL = forestry("mineral");
	public static final ResourceLocation VEINED = forestry("veined");
	public static final ResourceLocation CRYSTALLINE = forestry("crystalline");
	public static final ResourceLocation LUSTROUS = forestry("lustrous");
	public static final ResourceLocation OPULENT = forestry("opulent");
	public static final ResourceLocation BURNISHED = forestry("burnished");
	public static final ResourceLocation GLISTENING = forestry("glistening");
	public static final ResourceLocation PULSATING = forestry("pulsating");
	public static final ResourceLocation CARBONISED = forestry("carbonised");
	public static final ResourceLocation BRILLIANT = forestry("brilliant");
	public static final ResourceLocation ENVIOUS = forestry("envious");
	public static final ResourceLocation SERENE = forestry("serene");
	public static final ResourceLocation CERULEAN = forestry("cerulean");
	public static final ResourceLocation CONDUCTIVE = forestry("conductive");
	public static final ResourceLocation STANNOUS = forestry("stannous");
	public static final ResourceLocation STALWART = forestry("stalwart");
	public static final ResourceLocation REGAL = forestry("regal");
}
